### PR TITLE
Several improvements to CoNVaDING

### PR DESCRIPTION
**Pull request by duartemolha**
Hi ...

I hope you don't mind me playing around with your code... but that is the beauty of open source, correct :)

Here are the main changes/ improvements I have implemented:

1. Added support for pipeline mode where the entire script runs in sequence based on input BAM files or Counts and a folder of preprocessed controls;

    - I have implemented 2 pipeline modes PipelineFromBams and PipelineFromCounts, these take as input a folder of bam samples or counts, respectively and run the whole process from normalization, selection of best controls, generating TargetQcList file and creating the final list
    - Added a mode "addToControls" that, as the name indicates, just takes an input folder of bams and adds the counts for each to a controls folder. A more simplified way of running the same as StartWithBand including sampleAsControl parameter

2. Added support to detailing intervals within targets by using the score filed on the Bed file;

    - One of the things that I thought as a bit bad about the input bed file for CoNVaDING was that the name of the bed file needed to be the same for each gene being targeted. This way the output of the found regions would call the intervals but it did not indicated with of the parts of the gene where affected (ie exon1).
What I have implemented is support for using the 5th column of the input bed file to display the region being affected, for example:

> 16 23641109 23641310 PALB2 exon1 -
> 16 23638069 23638129 PALB2 exon2 -
> 16 23637849 23637952 PALB2 exon3 -
> 16 23634861 23636334 PALB2 exon4 -

this way the output contains both the start and end of the aberration but also the exons affected:

> 16 23641109 23638129 PALB2 exon1-exon2

3. in addition to the regular text files output, the script now also outputs a bed files for all abberations included in each file (long, short and final); These bed files use the GFFtag formating for [IGV](https://software.broadinstitute.org/software/igv/feature_track_options) to allow it to display all metadata associated with the call on hovering (i.e n targets, shappiro passed targets, etc...)

4. Converted from using hardcoded temporary files and used [FILE::Temp](https://perldoc.perl.org/File/Temp.html) perl module instead that deals automatically with temp file cleanup

5.LOTS AND LOTS OF code cleanup and removal of global variables that made the code difficult to understand and run on a pipeline mode as variables would get rewritten in a non-trivial way

I have increased the version to 1.2.2 as the feature set is almost identical but there is a LOT of code that has been changed. I hope this helps you.

### CODE REVIEW

**Comment by duartemolha** [comment]
if the aberration affected more than 2 sequential targets the output would say:

> 16 23641109 23637952 PALB2 exon1-exon3

**Comment by ljohansson** [comment]
How would you address different isoforms in the extra column?

**Comment by duartemolha** [comment]
The column is suppose to be free text. You decide what you write for every
target on your bed file.

The only way I see more robust reporting of what is affected is to take the
reported interval of the abberation and maybe run it though a database API
such as ensembl to have a comprehensive report of what it affects

On 12 Oct 2017 08:22, "ljohansson" <notifications@github.com> wrote:

How would you address different isoforms in the extra column?

—
You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub
<https://github.com/molgenis/CoNVaDING/pull/35#issuecomment-336043317>, or mute
the thread

**Comment by duartemolha** [comment]
Or maybe use the rest api to retrieve that data if you don't want to create
a dependency of having to install the ensembl perl API.

It certainly is doable if you want to go down that path... however this
will also involve requiring the user to tell the software what assembly the
bam files are mapped to or detect it somehow from the mapping to the
sequence to the coordinates.





[image: --]
Duarte Molha
[image: https://]about.me/duarte
<https://about.me/duarte?promo=email_sig>

**Comment by duartemolha** [comment]
As for addressing isoforms, I did not put any length limit on the string for that column... So you could (if you so wish) describe every exon as what transcript it affects...

Something like 

16 23641109 23641310 PALB2 TranscriptID1:exon1;TranscriptID2:exon2 -
16 23638069 23638129 PALB2 TranscriptID2:exon3 -
16 23637849 23637952 PALB2 TranscriptID1:exon2;TranscriptID2:exon4  -
16 23634861 23636334 PALB2 TranscriptID1:exon4 -

In this case if the aberration affected the first 2 targets in this bed file the output would say:
16 23641109 23638129 PALB2 TranscriptID1:exon1;TranscriptID2:exon2-TranscriptID2:exon3

Sure it is not the most pretty output and it could be missing all the isoforms it affects, for example the following aberration 

16 23638069 23636334 PALB2 TranscriptID2:exon3-TranscriptID1:exon4 

would be missing the information that it affects also TranscriptID2:exon4

But I am ok with this as I know that all targets between the 2 reported targets are implicated.

We could instead implement it as you described by listing all affected targets like:

16 23638069 23636334 PALB2 TranscriptID2:exon3;TranscriptID1:exon2;TranscriptID2:exon4;TranscriptID1:exon4 

If is justv a question of changing a very small section of the code

But I do not think that is very pretty :)

**Comment by duartemolha** [comment]
also ... any addition of REST api or any other type of remote database query will obviously require a working database connection.

**Comment by ljohansson** [comment]
I'm not a big fan of adding extra dependencies (the less the better). 
Adding the extra annotation can also be done post-analysis. Personally I would leave this step outside the CoNVaDING framework.

**Comment by duartemolha** [comment]
Agreed.. that is why I did not add it :)

**Comment by duartemolha** [comment]
However... I will keep that additional field on my fork... if you wish to remove on your end I am happy to go through your code after the merge and remove it.

**Comment by duartemolha** [comment]
I will be working on additional changes to this. Since you do not seem keen on some of this changes I am closing this pull request .

All the best

**Comment by ljohansson** [comment]
Dear Duarte, 
We greatly appreciate your work on improving CoNVaDING. However, due to busy work schedules we are not able to spend much time on CoNVaDING development and validation. Because we want to do a full validation on each new version, accepting pull requests is quite an extensive process. However, we are currently discussing the possibility to add a location for unvalidated releases. So that your CoNVaDING version can be hosted from there. In a later stage we could then incorporate parts (or whole) of the changes in an official release.
Best regards,
Lennart

**Comment by duartemolha** [comment]
no problem... but to be fair... that is what forks are all about - "unvalidaded versions of CoNVaDING" :-) 

I will continue, hopefully, in my spare time to improve on my version. Feel free to pull from it whatever you think makes sense for you.

**Pull request closed without merging**
